### ISSUE TITLE
Can you provide the best pretrained SVM model?

### ISSUE THREAD

**Issue by nikifori** [vntkumar8/musical-instrument-classification#1]

**Comment by vntkumar8** [comment]
Hi, we don't have any pre-trained model available. The code to replicate the results can be accesed [here](https://github.com/vntkumar8/musical-instrument-classification/blob/master/codes/CDSProject-Essentia.ipynb)

Here is the [manuscript](https://arxiv.org/abs/1912.02606) with all technical details and commentary. 
CC: @KarthikeyaR
